name: 'Terraform GCP Deployment'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 1: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    # Step 2: Create a temporary file for the service account key
    - name: Write GCP Service Account Key to file
      run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > ./account.json

    # Step 3: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Plan Terraform changes
    - name: Terraform Plan
      run: terraform plan -input=false

    # Step 6: Apply Terraform changes (only on push to main branch)
    - name: Terraform Apply
    
      run: terraform apply -auto-approve
