name: 'Terraform GCP Deployment'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      env:
       GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    # Step 3: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Plan Terraform changes
    - name: Terraform Plan
      run: terraform plan -input=false

    # Step 6: Apply Terraform changes (only on push to main branch)
    - name: Terraform Apply
    
      run: terraform apply -auto-approve
